name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run Tests
        run: npm test

      # Step 5: Build (optional for Node.js)
      - name: Build
        run: echo "No build step for this simple app"

      # Step 6: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "HelloCloudApp"
          environment_name: "HelloCloudApp-env"
          region: "us-east-1"
          version_label: "v1-${{ github.sha }}"
          bucket_name: "elasticbeanstalk-eu-north-1-493608842287"
